multi_api_platform:
  apis:
    external:
      namespace: ~
      implements: ~
      conditions: ~
      debug_conditions: ~
    internal:
      namespace: ~
      implements: ~
      conditions: ~
      debug_conditions: ~